name: 'schoolweek.ru'

services:
  
  app:
    build: .
    environment:
      DB_HOST: 'mariadb'
      DB_NAME: 'schoolweek'
      DB_PASS: 'kt0XCknc6gEzjapD'
    container_name: 'app-schoolweek.ru'
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kt0XCknc6gEzjapD
    volumes:
      - mongo_data:/data/db
    container_name: 'mongo-schoolweek.ru'

volumes:
  mongo_data:
