name: 'schoolweek.ru'

services:

  app:
    build: .
    environment:
      MONGO_URI: 'mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/schoolweek?authSource=admin'
    depends_on:
      - mongodb
    container_name: 'app-schoolweek.ru'

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD}'
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    container_name: 'mongo-schoolweek.ru'

volumes:
  mongo_data:
